# Generated by Django 2.1.15 on 2020-11-21 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=1000)),
                ('c1', models.CharField(max_length=100)),
                ('c2', models.CharField(max_length=100)),
                ('c3', models.CharField(max_length=100)),
                ('c4', models.CharField(max_length=100)),
                ('c', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'quiz_qna',
            },
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_score',
            },
        ),
    ]
